import './globals.css'
import type { Metadata } from 'next'
import { Quicksand } from 'next/font/google'
import { Providers } from './providers'

const quickSand = Quicksand({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={quickSand.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
